### ISSUE TITLE
elf2e32 can't handle argument put in double quotes

### ISSUE THREAD

**Issue by pent0** [fedor4ever/elf2e32#4]
Original tools work just fine.
For example, if i put 
``
--elfinput="C:\Test ELF\test.elf"
``
It will just gives an exception: ```elf2e32 : Error: E1001: Could not open file : "C:\Test ELF\test.elf". ``` Remove the double quotes work

**Comment by fedor4ever** [comment]
Looks strange, thanks. I check at evening.
Fiodar Stryzhniou

исходное сбщ
Тема: [fedor4ever/elf2e32] elf2e32 can't handle argument put in double quotes (#4)
От: pent0 <notifications@github.com>
Дата: 17.01.2019 14.37

Original tools work just fine.
For example, if i put 
``
--elfinput="C:\Test ELF\test.elf"
``
It will just gives an exception: ```elf2e32 : Error: E1001: Could not open file : "C:\Test ELF\test.elf". ``` Remove the double quotes work

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/fedor4ever/elf2e32/issues/4

**Comment by fedor4ever** [comment]
@pent0, it works for me. How you build it?

I use these options to run in Codeblock with mingw:
--capability=All-TCB --definput="D:\codeblock\elf2e32\tests\libcryptou.def" --defoutput="tests\tmp\out.def" --elfinput="D:\codeblock\elf2e32\tests\libcrypto.dll" --output="tests\tmp\libcrypto-2.4.5.tst.dll" --libpath="tests\SDK_libs" --linkas="libcrypto{000a0000}.dll" --dso="tests\tmp\libcrypto{000a0000}.dso" --fpu=softvfp --uid1=0x10000079 --uid2=0x20004c45 --uid3=0x00000000 --targettype=STDDLL --namedlookup --dlldata --ignorenoncallable --debuggable --smpsafe --uncompressed

**Comment by pent0** [comment]
That's weird, I can't reproduce it. My path was really long but I don't think it is related. Closing this.
